import { useState } from 'react';
import { Sparkles, Plus, Upload, Download, Scissors, Merge, Trash2, BookmarkPlus, Check, AlertTriangle } from 'lucide-react';
import type { Project, Status, Style } from '../types';
import { presets, defaultStyle, uid, duration } from '../../shared/project.mjs';
import { IconButton } from './Controls';
type Props={project:Project;status:Status|null;selected:string|null;time:number;change:(p:Project)=>void;select:(id:string)=>void;seek:(t:number)=>void;generate:()=>void;importSrt:()=>void;exportCues:(format:'srt'|'ass')=>void;savePreset:(name:string)=>void;editStyle:()=>void;busy:boolean};
export default function CaptionsPanel({project:p,status,selected,time,change,select,seek,generate,importSrt,exportCues,savePreset,editStyle,busy}:Props) {
  const [pane,setPane]=useState<'captions'|'presets'>('captions'),[name,setName]=useState('');
  const cue=p.captions.find(c=>c.id===selected);
  const styles=[...presets.map(x=>({name:x.name,style:{...defaultStyle(),...x.style} as Style})),...(status?.presets||[])];
  const split=()=>{if(!cue)return;const at=time>cue.start&&time<cue.end?time:(cue.start+cue.end)/2;const words=cue.text.split(/\s+/),n=Math.max(1,Math.round(words.length*(at-cue.start)/(cue.end-cue.start)));const next=structuredClone(p),index=next.captions.findIndex(c=>c.id===cue.id);next.captions.splice(index,1,{...cue,end:at,text:words.slice(0,n).join(' ')},{...cue,id:uid(),start:at,text:words.slice(n).join(' ')||'…'});change(next);};
  const merge=()=>{if(!cue)return;const sorted=[...p.captions].sort((a,b)=>a.start-b.start),index=sorted.findIndex(c=>c.id===cue.id),other=sorted[index+1];if(!other)return;const next=structuredClone(p);Object.assign(next.captions.find(c=>c.id===cue.id)!,{end:other.end,text:cue.text.replace(/\n/g,' ')+' '+other.text.replace(/\n/g,' ')});next.captions=next.captions.filter(c=>c.id!==other.id);change(next);};
  return <div className="captions-panel"><div className="panel-heading"><div><h2>Subtítulos</h2><p>Tu voz, con tu estilo.</p></div><span className="tiny-tag">LOCAL</span></div>
    <button className="button primary full" onClick={generate} disabled={busy||!p.clips.length}><Sparkles size={15}/> Generar subtítulos</button><p className="caption-description">Reconocimiento de voz en español. Todo se procesa en tu ordenador.</p>
    {p.captionStale&&<div className="inline-warning"><AlertTriangle size={14}/><span>La edición ha cambiado. Revisa los tiempos o regenera el tramo afectado.</span><button title="Marcar subtítulos revisados" onClick={()=>change({...p,captionStale:false})}><Check size={14}/></button></div>}
    <div className="panel-tabs"><button className={pane==='captions'?'selected':''} onClick={()=>setPane('captions')}>Transcripción <span>{p.captions.length}</span></button><button className={pane==='presets'?'selected':''} onClick={()=>setPane('presets')}>Estilos</button></div>
    {pane==='presets'?<><div className="preset-grid">{styles.map(s=><button key={s.name} aria-label={s.name} className={`preset ${JSON.stringify(p.captionStyle)===JSON.stringify(s.style)?'chosen':''}`} onClick={()=>{change({...p,captionStyle:structuredClone(s.style)});editStyle();}}><div style={{background:s.style.backgroundOpacity?s.style.background:'#26292c'}}><span style={{color:s.style.color,fontWeight:s.style.bold?800:400,textShadow:s.style.outline?'-1px -1px 0 #000,1px 1px 0 #000':undefined}}>Tu historia</span></div><small>{s.name}</small></button>)}</div><button className="button secondary full" onClick={editStyle}>Personalizar estilo</button><div className="save-preset"><input placeholder="Nombre de tu estilo" value={name} onChange={e=>setName(e.target.value)}/><IconButton title="Guardar estilo" onClick={()=>{if(name.trim()){savePreset(name);setName('');}}}><BookmarkPlus size={16}/></IconButton></div></>:<>
      <div className="caption-tools"><IconButton title="Añadir subtítulo" onClick={()=>{const c={id:uid(),start:time,end:time+2,text:'Escribe tu subtítulo'};change({...p,captions:[...p.captions,c]});select(c.id);}}><Plus size={15}/></IconButton><IconButton title="Dividir subtítulo" onClick={split} disabled={!cue}><Scissors size={15}/></IconButton><IconButton title="Unir con el siguiente" onClick={merge} disabled={!cue}><Merge size={15}/></IconButton><IconButton title="Eliminar subtítulo" onClick={()=>change({...p,captions:p.captions.filter(c=>c.id!==selected)})} disabled={!cue}><Trash2 size={15}/></IconButton><span/><IconButton title="Importar SRT" onClick={importSrt}><Upload size={15}/></IconButton><IconButton title="Exportar SRT" onClick={()=>exportCues('srt')} disabled={!p.captions.length}><Download size={15}/></IconButton></div>
      <div className="caption-list">{[...p.captions].sort((a,b)=>a.start-b.start).map((c,i)=><div key={c.id} className={`caption-card ${selected===c.id?'selected':''} ${time>=c.start&&time<c.end?'current':''}`} onClick={()=>select(c.id)}><div className="caption-card-head"><span>{String(i+1).padStart(2,'0')}</span><button onClick={()=>seek(c.start)}>{c.start.toFixed(2)} — {c.end.toFixed(2)}</button></div><textarea aria-label={`Subtítulo ${i+1}`} rows={2} value={c.text} onChange={e=>{const next=structuredClone(p);next.captions.find(x=>x.id===c.id)!.text=e.target.value;change(next);}}/></div>)}{!p.captions.length&&<div className="empty-captions"><span className="cc-large">CC</span><h3>Haz que te lean</h3><p>Genera subtítulos desde tu voz, importa un SRT o escribe los tuyos.</p><button onClick={importSrt}>Importar archivo SRT</button></div>}</div>
      <div className="caption-export"><button onClick={()=>exportCues('ass')} disabled={!p.captions.length}>Exportar ASS con estilos</button><span>{duration(p)>0?'Sin marcas de agua':''}</span></div>
    </>}
  </div>;
}
