import type { ReactNode } from 'react';
import { AlignCenter, AlignLeft, AlignRight, Bold, Italic, Plus } from 'lucide-react';
import type { Style, Status } from '../types';
export function IconButton({ children, title, onClick, disabled=false, active=false }: {children:ReactNode;title:string;onClick:()=>void;disabled?:boolean;active?:boolean}) {return <button className={`icon-button ${active?'active':''}`} title={title} aria-label={title} onClick={onClick} disabled={disabled}>{children}</button>;}
export function Field({label,children}:{label:string;children:ReactNode}) {return <label className="field"><span>{label}</span>{children}</label>;}
export function NumberField({label,value,onChange,min=0,max=10000,step=0.1}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;step?:number}) {return <Field label={label}><input type="number" value={Number(value.toFixed(3))} min={min} max={max} step={step} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n))onChange(Math.max(min,Math.min(max,n)));}}/></Field>;}
export function Slider({label,value,min,max,step=0.01,onChange,suffix='',display}:{label:string;value:number;min:number;max:number;step?:number;onChange:(n:number)=>void;suffix?:string;display?:string}) {return <label className="slider-field"><span>{label}<b>{display??Number(value.toFixed(2))}{suffix}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;}
export function StyleEditor({style,change,status,onFont}:{style:Style;change:(patch:Partial<Style>)=>void;status:Status|null;onFont:()=>void}) {
  const families=[...new Set(['Inter','Arial','Georgia','Impact',...(status?.fonts.map(f=>f.name)||[])])].sort();
  return <div className="style-editor">
    <div className="font-row"><Field label="Fuente"><select value={style.font} onChange={e=>change({font:e.target.value})}>{families.map(f=><option key={f}>{f}</option>)}</select></Field><IconButton title="Añadir fuente TTF u OTF" onClick={onFont}><Plus size={16}/></IconButton></div>
    <div className="field-grid"><NumberField label="Tamaño" value={style.size} min={12} max={180} step={1} onChange={size=>change({size})}/><Field label="Color"><input type="color" value={style.color} onChange={e=>change({color:e.target.value})}/></Field></div>
    <div className="segmented"><IconButton title="Negrita" active={style.bold} onClick={()=>change({bold:!style.bold})}><Bold size={16}/></IconButton><IconButton title="Cursiva" active={style.italic} onClick={()=>change({italic:!style.italic})}><Italic size={16}/></IconButton><span className="separator"/>{(['left','center','right'] as const).map((a,i)=><IconButton key={a} title={['Alinear izquierda','Centrar','Alinear derecha'][i]} active={style.align===a} onClick={()=>change({align:a})}>{[<AlignLeft size={16}/>,<AlignCenter size={16}/>,<AlignRight size={16}/>][i]}</IconButton>)}</div>
    <div className="field-grid"><NumberField label="Borde" value={style.outline} max={12} step={1} onChange={outline=>change({outline})}/><Field label="Color del borde"><input type="color" value={style.outlineColor} onChange={e=>change({outlineColor:e.target.value})}/></Field></div>
    <div className="field-grid"><NumberField label="Sombra" value={style.shadow} max={15} step={1} onChange={shadow=>change({shadow})}/><NumberField label="Espaciado" value={style.spacing} min={-5} max={20} step={1} onChange={spacing=>change({spacing})}/></div>
    <div className="field-grid"><Field label="Fondo"><input type="color" value={style.background} onChange={e=>change({background:e.target.value})}/></Field><NumberField label="Margen del fondo" value={style.padding} max={40} step={1} onChange={padding=>change({padding})}/></div>
    <Slider label="Opacidad del fondo" value={style.backgroundOpacity} min={0} max={1} onChange={backgroundOpacity=>change({backgroundOpacity})} display={`${Math.round(style.backgroundOpacity*100)}%`}/>
    <div className="field-grid"><NumberField label="Posición X (%)" value={style.x*100} max={100} step={1} onChange={x=>change({x:x/100})}/><NumberField label="Posición Y (%)" value={style.y*100} max={100} step={1} onChange={y=>change({y:y/100})}/></div>
    <div className="segmented positions">{[['Arriba',0.18],['Centro',0.5],['Abajo',0.88]].map(([label,y])=><button key={label} onClick={()=>change({y:Number(y)})}>{label}</button>)}</div>
  </div>;
}
