import { Film, Music2, Type, SlidersHorizontal, Copy, Trash2, Link2, Link2Off, RotateCcw } from 'lucide-react';
import type { Project, Clip, Status, Style } from '../types';
import { defaultStyle } from '../../shared/project.mjs';
import { cornerPlacement } from '../../shared/placement.mjs';
import { Field, NumberField, Slider, StyleEditor, IconButton } from './Controls';
type Props={project:Project;selected:string|null;status:Status|null;update:(id:string,patch:Partial<Clip>)=>void;change:(p:Project)=>void;onFont:()=>void;duplicate:()=>void;remove:()=>void;detach:()=>void;tab:'properties'|'style';setTab:(t:'properties'|'style')=>void};
export default function Inspector({project:p,selected,status,update,change,onFont,duplicate,remove,detach,tab,setTab}:Props) {
  const clip=p.clips.find(c=>c.id===selected),cue=p.captions.find(c=>c.id===selected),m=p.media.find(m=>m.id===clip?.mediaId),locked=clip&&p.tracks.find(t=>t.id===clip.trackId)?.locked;
  const style=(cue?.style||clip?.style||p.captionStyle) as Style;
  const styleChange=(patch:Partial<Style>)=>{if(clip)update(clip.id,{style:{...(clip.style||defaultStyle()),...patch}});else if(cue){const next=structuredClone(p);next.captions.find(c=>c.id===cue.id)!.style={...style,...patch};change(next);}else change({...p,captionStyle:{...p.captionStyle,...patch}});};
  return <aside className="inspector">
    <div className="panel-tabs"><button className={tab==='properties'?'selected':''} onClick={()=>setTab('properties')}>Propiedades</button><button className={tab==='style'?'selected':''} onClick={()=>setTab('style')}>Estilo de texto</button></div>
    <div className="inspector-scroll">
      {tab==='style'?<><div className="section-label">{cue?'ESTE SUBTÍTULO':clip?.text?'ESTE TEXTO':'TODOS LOS SUBTÍTULOS'}</div><StyleEditor style={style} change={styleChange} status={status} onFont={onFont}/>{cue&&<button className="button secondary full" onClick={()=>{const next=structuredClone(p);delete next.captions.find(c=>c.id===cue.id)!.style;change(next);}}>Usar el estilo general</button>}</>:cue?<>
        <div className="section-label">SUBTÍTULO</div><Field label="Texto"><textarea value={cue.text} rows={4} onChange={e=>{const next=structuredClone(p);next.captions.find(c=>c.id===cue.id)!.text=e.target.value;change(next);}}/></Field>
        <div className="field-grid"><NumberField label="Inicio (s)" value={cue.start} max={cue.end-0.05} onChange={start=>{const next=structuredClone(p);next.captions.find(c=>c.id===cue.id)!.start=start;change(next);}}/><NumberField label="Final (s)" value={cue.end} min={cue.start+0.05} onChange={end=>{const next=structuredClone(p);next.captions.find(c=>c.id===cue.id)!.end=end;change(next);}}/></div>
        <button className="button secondary full" onClick={()=>setTab('style')}>Personalizar este subtítulo</button><button className="button danger full" onClick={()=>change({...p,captions:p.captions.filter(c=>c.id!==cue.id)})}><Trash2 size={14}/> Eliminar subtítulo</button>
      </>:clip?<fieldset disabled={locked} className="inspector-fields">
        <div className="selected-file">{clip.text?<Type size={18}/>:m?.type==='audio'?<Music2 size={18}/>:<Film size={18}/>}<div><b>{clip.text?'Texto':clip.name}</b><span>{locked?'Pista bloqueada':m?.type==='image'?'Imagen':m?.type==='audio'?'Audio':clip.text?'Capa de texto':`${m?.width} × ${m?.height}`}</span></div></div>
        <div className="section-label">TIEMPO</div><div className="field-grid"><NumberField label="Inicio (s)" value={clip.start} onChange={start=>update(clip.id,{start})}/><NumberField label="Duración (s)" value={clip.duration} min={0.05} max={m&&m.type!=='image'?(m.duration-clip.in)/clip.speed:36000} onChange={duration=>update(clip.id,{duration})}/></div>
        <Field label="Pista"><select aria-label="Pista del clip" value={clip.trackId} onChange={e=>update(clip.id,{trackId:e.target.value})}>{p.tracks.filter(t=>t.kind===p.tracks.find(t=>t.id===clip.trackId)?.kind).map(t=><option key={t.id} value={t.id} disabled={t.locked&&t.id!==clip.trackId}>{t.name}{t.hidden?' · Oculta':''}</option>)}</select></Field>
        {m&&m.type!=='audio'&&<div className="layer-presets"><button onClick={()=>update(clip.id,{scale:1,x:0,y:0,rotation:0,fit:'contain'})}>Pantalla completa</button><button onClick={()=>update(clip.id,cornerPlacement(p,m) as Partial<Clip>)}>Colocar en una esquina</button></div>}
        {!clip.text&&m?.type!=='image'&&<NumberField label="Recorte del original (s)" value={clip.in} max={Math.max(0,(m?.duration||0)-clip.duration*clip.speed)} onChange={value=>update(clip.id,{in:value})}/>}
        {clip.text?<><div className="section-label">CONTENIDO</div><textarea rows={4} value={clip.text} onChange={e=>update(clip.id,{text:e.target.value})}/><button className="button secondary full" onClick={()=>setTab('style')}>Fuente y estilo</button></>:<>
        {m?.type!=='audio'&&<><div className="section-label">TRANSFORMACIÓN</div><div className="field-grid"><NumberField label="Posición X" value={clip.x} min={-p.width} max={p.width} step={1} onChange={x=>update(clip.id,{x})}/><NumberField label="Posición Y" value={clip.y} min={-p.height} max={p.height} step={1} onChange={y=>update(clip.id,{y})}/></div><Slider label="Escala" value={clip.scale} min={0.1} max={3} onChange={scale=>update(clip.id,{scale})} display={`${Math.round(clip.scale*100)}%`}/><NumberField label="Rotación" value={clip.rotation} min={-360} max={360} step={1} onChange={rotation=>update(clip.id,{rotation})}/><div className="segmented positions"><button className={clip.fit==='contain'?'chosen':''} onClick={()=>update(clip.id,{fit:'contain'})}>Ajustar</button><button className={clip.fit==='cover'?'chosen':''} onClick={()=>update(clip.id,{fit:'cover'})}>Rellenar</button><button title="Restablecer transformación" onClick={()=>update(clip.id,{x:0,y:0,scale:1,rotation:0})}><RotateCcw size={13}/></button></div><Slider label="Opacidad" value={clip.opacity} min={0} max={1} onChange={opacity=>update(clip.id,{opacity})}/>
          <div className="section-label">COLOR</div><Slider label="Brillo" value={clip.brightness} min={-0.5} max={0.5} onChange={brightness=>update(clip.id,{brightness})}/><Slider label="Contraste" value={clip.contrast} min={0.2} max={2} onChange={contrast=>update(clip.id,{contrast})}/><Slider label="Saturación" value={clip.saturation} min={0} max={2} onChange={saturation=>update(clip.id,{saturation})}/>
          <div className="section-label">TRANSICIÓN</div><Field label="Tipo"><select value={clip.transition} onChange={e=>{const type=e.target.value as Clip['transition'];const next=structuredClone(p),target=next.clips.find(c=>c.id===clip.id)!;target.transition=type;if(type==='dissolve'){const previous=next.clips.filter(c=>c.trackId===clip.trackId&&c.id!==clip.id&&c.start<clip.start).sort((a,b)=>b.start-a.start)[0];if(previous){target.start=Math.max(previous.start,previous.start+previous.duration-target.transitionDuration);if(next.captions.length)next.captionStale=true;}}change(next);}}><option value="none">Sin transición</option><option value="black">Fundido al fondo</option><option value="dissolve">Disolución con el clip anterior</option></select></Field>{clip.transition!=='none'&&<NumberField label="Duración (s)" value={clip.transitionDuration} min={0.1} max={Math.min(3,clip.duration)} onChange={transitionDuration=>update(clip.id,{transitionDuration})}/>}</>}
        {m?.type!=='image'&&<><div className="section-label">VELOCIDAD</div><Field label="Reproducción"><select value={clip.speed} onChange={e=>{const speed=Number(e.target.value);update(clip.id,{speed,duration:clip.duration*clip.speed/speed});}}>{[0.25,0.5,0.75,1,1.25,1.5,2,3,4].map(s=><option key={s} value={s}>{s}×{s===1?' · Normal':''}</option>)}</select></Field></>}
        {m?.hasAudio&&<><div className="section-label">AUDIO</div><Slider label="Volumen" value={clip.volume} min={0} max={1} onChange={volume=>update(clip.id,{volume})} display={`${Math.round(clip.volume*100)}%`}/><label className="checkbox"><input type="checkbox" checked={clip.muted} onChange={e=>update(clip.id,{muted:e.target.checked})}/> Silenciar clip</label><div className="field-grid"><NumberField label="Entrada (s)" value={clip.fadeIn} max={clip.duration} onChange={fadeIn=>update(clip.id,{fadeIn})}/><NumberField label="Salida (s)" value={clip.fadeOut} max={clip.duration} onChange={fadeOut=>update(clip.id,{fadeOut})}/></div>{m.type==='video'&&<button className="button secondary full" onClick={detach}><Music2 size={14}/> Separar audio</button>}</>}
        </>}
        {clip.linkId&&<button className="button secondary full" onClick={()=>{const next=structuredClone(p);for(const c of next.clips)if(c.linkId===clip.linkId)delete c.linkId;change(next);}}><Link2Off size={14}/> Desvincular clips</button>}
        <div className="inspector-bottom"><button className="button secondary" onClick={duplicate}><Copy size={14}/> Duplicar</button><IconButton title="Eliminar clip" onClick={remove}><Trash2 size={15}/></IconButton></div>
      </fieldset>:<div className="inspector-empty"><SlidersHorizontal size={26} strokeWidth={1}/><h3>Cada detalle cuenta</h3><p>Selecciona un clip para ajustar su imagen, sonido y duración.</p><div className="project-info"><span>LIENZO</span><b>{p.width} × {p.height}</b><span>FOTOGRAMAS</span><b>{p.fps} fps</b><span>PROCESAMIENTO</span><b>100% local</b></div></div>}
    </div>
  </aside>;
}
