import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, Check, ChevronDown, Clapperboard, Copy, Download, Film, FolderOpen, HardDrive, Image, Keyboard, LoaderCircle, Maximize2, Merge, Minus, Monitor, Music2, Pause, Play, Plus, Redo2, Save, Scissors, Settings, ShieldCheck, SkipBack, SkipForward, Sparkles, Trash2, Type, Undo2, X, Captions, ChevronLeft, ChevronRight, Package } from 'lucide-react';
import type { Clip, ExportOptions, Job, Media, Project, Status, Track } from './types';
import { defaultStyle, deleteClip, duration, newClip, newProject, splitClip, timecode, uid } from '../shared/project.mjs';
import { Layers } from 'lucide-react';
import { placeMedia } from '../shared/placement.mjs';
import { Field, IconButton, NumberField } from './components/Controls';
import Timeline from './components/Timeline';
import Preview from './components/Preview';
import Inspector from './components/Inspector';
import CaptionsPanel from './components/CaptionsPanel';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/inter/latin-700.css';
const api=window.corte;
const initial=newProject() as Project;
type Modal='settings'|'export'|'transcribe'|'projects'|'shortcuts'|'recovery'|null;
type Placement={trackId?:string;start:number;overlay?:boolean};
export default function App() {
  const [project,setProject]=useState<Project>(initial),[selected,setSelected]=useState<string|null>(null),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[zoom,setZoom]=useState(45),[leftTab,setLeftTab]=useState('media'),[inspectorTab,setInspectorTab]=useState<'properties'|'style'>('properties');
  const [loading,setLoading]=useState(!!api);
  const [modal,setModal]=useState<Modal>(null),[status,setStatus]=useState<Status|null>(null),[filePath,setFilePath]=useState<string>(),[dirty,setDirty]=useState(false),[saveState,setSaveState]=useState('Proyecto nuevo'),[jobs,setJobs]=useState<Job[]>([]),[notice,setNotice]=useState<{text:string;error:boolean}|null>(null),[importing,setImporting]=useState(false),[fileMenu,setFileMenu]=useState(false),[search,setSearch]=useState('');
  const [preview,setPreview]=useState<{url:string;start:number;end:number}|null>(null),[historySize,setHistorySize]=useState([0,0]),[model,setModel]=useState('small'),[voiceTracks,setVoiceTracks]=useState<string[]>([]),[transcribeRange,setTranscribeRange]=useState({start:0,end:0}),[replaceCaptions,setReplaceCaptions]=useState(false),[exportOptions,setExportOptions]=useState<ExportOptions>({height:1080,fps:30,quality:'high',burnCaptions:true,normalize:false,start:0,end:0});
  const undo=useRef<Project[]>([]),redo=useRef<Project[]>([]),pRef=useRef(project),timeRef=useRef(time),timer=useRef<ReturnType<typeof setTimeout>|null>(null),transcribeSnapshot=useRef('');
  const total=duration(project),activeJobs=jobs.filter(j=>j.state==='running'),busy=activeJobs.length>0;
  pRef.current=project;timeRef.current=time;
  const notify=useCallback((text:string,error=false)=>{setNotice({text,error});if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setNotice(null),error?12000:5000);},[]);
  const safe=useCallback(async<T,>(fn:()=>Promise<T>):Promise<T|undefined>=>{if(!api){notify('Abre Corte Local como aplicación de escritorio para utilizar los archivos y los motores locales.',true);return;}try{return await fn();}catch(e){notify((e as Error).message,true);}},[notify]);
  const refresh=useCallback(async()=>{const s=await safe(()=>api!.status());if(s)setStatus(s);return s;},[safe]);
  const change=useCallback((next:Project)=>{if(next===pRef.current)return;undo.current.push(pRef.current);if(undo.current.length>80)undo.current.shift();redo.current=[];setHistorySize([undo.current.length,0]);pRef.current=next;setProject(next);setDirty(true);setPreview(null);},[]);
  const updateClip=useCallback((id:string,patch:Partial<Clip>)=>{const p=structuredClone(pRef.current),c=p.clips.find(c=>c.id===id);if(!c||p.tracks.find(t=>t.id===c.trackId)?.locked)return;const old=structuredClone(c);Object.assign(c,patch);
    if(c.linkId)for(const other of p.clips.filter(x=>x.linkId===c.linkId&&x.id!==c.id)){if(patch.start!==undefined)other.start+=c.start-old.start;if(patch.in!==undefined)other.in=c.in;if(patch.duration!==undefined)other.duration=c.duration;if(patch.speed!==undefined)other.speed=c.speed;}
    if(p.captions.length&&['start','duration','in','speed'].some(k=>k in patch))p.captionStale=true;change(p);},[change]);
  const history=(direction:'undo'|'redo')=>{const source=direction==='undo'?undo.current:redo.current,dest=direction==='undo'?redo.current:undo.current;if(!source.length)return;dest.push(pRef.current);const p=source.pop()!;pRef.current=p;setProject(p);setHistorySize([undo.current.length,redo.current.length]);setDirty(true);setPreview(null);};
  const seek=(value:number)=>{setTime(Math.max(0,Math.min(total,value)));};
  function load(p:Project,path?:string) {setPlaying(false);setTime(0);setSelected(null);setProject(p);pRef.current=p;undo.current=[];redo.current=[];setHistorySize([0,0]);setDirty(false);setPreview(null);setFilePath(path);setSaveState(path?'Guardado':'Recuperado');setModal(null);setFileMenu(false);}
  useEffect(()=>{if(!api)return;let alive=true;api.status().then(s=>{if(!alive)return;setStatus(s);if(s.recovery)setModal('recovery');setLoading(false);}).catch(e=>{setLoading(false);notify(e.message,true);});const unsub=api.onJob(j=>{setJobs(prev=>[...prev.filter(x=>x.id!==j.id),j]);if(j.state==='error')notify(j.message,true);if(j.state==='done'){
    if(j.kind==='export'){notify('Vídeo exportado correctamente.');}
    if(j.kind==='download'){refresh();notify(typeof j.result==='string'?j.result:'Descarga completada.');}
    if(j.kind==='preview'){setPreview(j.result);setTime(j.result.start);setPlaying(false);}
    if(j.kind==='transcribe'){const p=structuredClone(pRef.current);if(p.id!==j.result.projectId){notify('La transcripción pertenece a otro proyecto. Vuelve a abrirlo para regenerarla.',true);return;}
      if(JSON.stringify({clips:p.clips,tracks:p.tracks})!==transcribeSnapshot.current){notify('La edición cambió durante la transcripción. Regenera los subtítulos para sincronizarlos.',true);return;}
      p.captions=[...p.captions.filter(c=>c.end<=j.result.start||c.start>=j.result.end),...j.result.captions].sort((a,b)=>a.start-b.start);p.captionStale=false;change(p);setLeftTab('captions');notify(j.result.captions.length?`${j.result.captions.length} subtítulos generados. Revisa el texto antes de exportar.`:'No se ha detectado voz en el tramo seleccionado.');}
  }});return()=>{alive=false;unsub();};},[]);
  useEffect(()=>{if(!dirty||!api)return;const timer=setTimeout(()=>{api.autosave(project).then(()=>setSaveState('Autoguardado local')).catch(e=>notify(e.message,true));},900);return()=>clearTimeout(timer);},[project,dirty,notify]);
  useEffect(()=>{if(!playing)return;let frame:number;let previous=performance.now();const tick=(now:number)=>{const delta=(now-previous)/1000;previous=now;setTime(t=>{const next=t+delta;if(next>=(preview?.end||total)){setPlaying(false);return preview?.end||total;}return next;});frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,total,preview]);
  useEffect(()=>{if(time>total)setTime(total);},[total]);
  const addTrack=(kind:Track['kind'])=>{const p=structuredClone(project);p.tracks.unshift({id:uid(),name:`${kind==='video'?'Vídeo':kind==='audio'?'Audio':'Texto'} ${p.tracks.filter(t=>t.kind===kind).length+1}`,kind,hidden:false,muted:false,locked:false});change(p);};
  function addMedia(id:string,trackId?:string,start?:number,overlay=false) {
    try {
      const p=placeMedia(pRef.current,id,{trackId,start,overlay}) as Project;
      change(p);setSelected(p.clips.at(-1)!.id);setInspectorTab('properties');
      if(overlay){setPlaying(false);setTime(start??timeRef.current);scrollToTopTrack();}
    } catch(e){notify((e as Error).message,true);}
  }
  function scrollToTopTrack() {requestAnimationFrame(()=>{const element=document.querySelector('.timeline-scroll');if(element)element.scrollTop=0;});}
  async function importFiles(paths?:string[],placement?:Placement) {
    if(importing)return;
    setImporting(true);setPlaying(false);
    const media=await safe(()=>api!.importMedia(paths));setImporting(false);
    if(!media?.length)return;
    let p=structuredClone(pRef.current);const empty=!p.clips.length;p.media.push(...media);
    if(placement) {
      let at=placement.start;let error='';
      for(const m of media)try {
        p=placeMedia(p,m.id,{...placement,start:at}) as Project;
        if(!placement.overlay)at+=p.clips.at(-1)!.duration;
      } catch(e){error=(e as Error).message;}
      if(p.clips.length>pRef.current.clips.length){setSelected(p.clips.at(-1)!.id);setInspectorTab('properties');setTime(placement.start);}
      if(placement.overlay)scrollToTopTrack();
      if(error)notify(error,true);else notify(placement.overlay?'Capa añadida. Las pistas superiores se muestran encima de las inferiores.':'Archivos añadidos a la pista.');
    } else if(empty) {
      const m=media[0];p=placeMedia(p,m.id,{start:0}) as Project;setSelected(p.clips.at(-1)!.id);
    }
    if(empty&&p.clips.length&&media[0].type==='video'){const m=media[0],vertical=m.height>m.width;p.width=vertical?1080:1920;p.height=vertical?1920:1080;p.name=m.name.replace(/\.[^.]+$/,'');}
    change(p);
    if(!placement)notify(`${media.length} archivo${media.length>1?'s':''} importado${media.length>1?'s':''}.`);
  }
  function dropFiles(files:File[],trackId:string|undefined,start:number,overlay=false) {
    if(api)importFiles(files.map(file=>api.pathForFile(file)),{trackId,start,overlay});
  }
  function addText() {const p=structuredClone(project);let track=p.tracks.find(t=>t.kind==='text'&&!t.locked);if(!track){track={id:uid(),name:'Textos',kind:'text',hidden:false,muted:false,locked:false};p.tracks.unshift(track);}const c=newClip(null,track.id,time) as Clip;c.text='Tu historia';c.style={...defaultStyle(),y:0.5};p.clips.push(c);change(p);setSelected(c.id);setInspectorTab('style');}
  async function save(as=false,portable=false) {const snapshot=pRef.current;const file=await safe(()=>api!.saveProject(snapshot,as?undefined:filePath,portable));if(file){if(!portable){setFilePath(file);if(pRef.current===snapshot)setDirty(false);setSaveState('Guardado');}notify(portable?'Proyecto y archivos recopilados.':'Proyecto guardado.');refresh();}}
  async function open(file?:string) {if(dirty&&!window.confirm('Hay cambios sin guardar en el archivo del proyecto. ¿Abrir otro proyecto?'))return;setImporting(true);const result=await safe(()=>api!.openProject(file));setImporting(false);if(result){load(result.project,result.path);refresh();}}
  function newDocument() {if(dirty&&!window.confirm('¿Crear un proyecto nuevo? Guarda antes si quieres conservar el actual.'))return;load(newProject() as Project);setSaveState('Proyecto nuevo');safe(()=>api!.clearRecovery());}
  const remove=(ripple=false)=>{if(selected)change(deleteClip(project,selected,ripple) as Project);};
  function duplicate() {const c=project.clips.find(c=>c.id===selected);if(!c||project.tracks.find(t=>t.id===c.trackId)?.locked)return;const next=structuredClone(project),copy={...structuredClone(c),id:uid(),start:c.start+c.duration,linkId:undefined};next.clips.push(copy);change(next);setSelected(copy.id);}
  function detach() {const c=project.clips.find(c=>c.id===selected),m=project.media.find(m=>m.id===c?.mediaId);if(!c||!m?.hasAudio||project.tracks.find(t=>t.id===c.trackId)?.locked)return;const p=structuredClone(project);let track=p.tracks.find(t=>t.kind==='audio'&&!t.locked);if(!track){track={id:uid(),kind:'audio',name:'Audio separado',muted:false,hidden:false,locked:false};p.tracks.push(track);}const linkId=uid();const source=p.clips.find(x=>x.id===c.id)!;source.muted=true;source.linkId=linkId;p.clips.push({...structuredClone(c),id:uid(),trackId:track.id,muted:false,linkId});change(p);}
  function mergeClips() {const c=project.clips.find(c=>c.id===selected);if(!c||project.tracks.find(t=>t.id===c.trackId)?.locked)return;const next=project.clips.find(x=>x.id!==c.id&&x.trackId===c.trackId&&Math.abs(x.start-c.start-c.duration)<0.04&&x.mediaId===c.mediaId&&x.speed===c.speed&&Math.abs(x.in-c.in-c.duration*c.speed)<0.04);if(!next){notify('Para unir, selecciona dos cortes consecutivos del mismo original, con la misma velocidad.',true);return;}const p=structuredClone(project);p.clips.find(x=>x.id===c.id)!.duration+=next.duration;p.clips=p.clips.filter(x=>x.id!==next.id);change(p);}
  async function addFont() {const font=await safe(()=>api!.addFont());if(font){setStatus(s=>s?{...s,fonts:[...s.fonts,font]}:s);notify(`Fuente ${font.name} añadida.`);}}
  function showTranscribe() {setPlaying(false);setVoiceTracks(project.tracks.filter(t=>project.clips.some(c=>c.trackId===t.id&&!c.muted&&project.media.find(m=>m.id===c.mediaId)?.hasAudio)&&!t.muted).map(t=>t.id));setTranscribeRange({start:0,end:total});setReplaceCaptions(false);setModal('transcribe');}
  async function transcribe() {if(project.captions.some(c=>c.end>transcribeRange.start&&c.start<transcribeRange.end)&&!replaceCaptions){notify('Confirma la sustitución de los subtítulos del tramo para conservar el control de tus correcciones.',true);return;}transcribeSnapshot.current=JSON.stringify({clips:project.clips,tracks:project.tracks});const effectiveModel=status?.models.includes(model)?model:status?.models[0]||model;const job=await safe(()=>api!.transcribe(project,effectiveModel,voiceTracks,transcribeRange.start,transcribeRange.end));if(job)setModal(null);}
  async function renderPreview() {setPlaying(false);const start=Math.min(time,Math.max(0,total-0.05)),end=Math.min(total,start+10);const id=await safe(()=>api!.renderPreview(project,start,end));if(id)notify('Preparando una vista renderizada de hasta 10 segundos…');}
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&(e.target.matches('input,textarea,select')||e.target.isContentEditable))return;if(modal)return;
    if((e.ctrlKey||e.metaKey)&&e.code==='KeyS'){e.preventDefault();save(e.shiftKey);return;}
    if((e.ctrlKey||e.metaKey)&&e.code==='KeyZ'){e.preventDefault();history(e.shiftKey?'redo':'undo');return;}
    if((e.ctrlKey||e.metaKey)&&e.code==='KeyY'){e.preventDefault();history('redo');return;}
    if((e.ctrlKey||e.metaKey)&&e.code==='KeyD'){e.preventDefault();duplicate();return;}
    if(e.code==='Space'){e.preventDefault();if(total)setPlaying(v=>!v);}
    if(e.code==='ArrowRight'){e.preventDefault();setPlaying(false);seek(time+1/project.fps);}
    if(e.code==='ArrowLeft'){e.preventDefault();setPlaying(false);seek(time-1/project.fps);}
    if(e.code==='KeyB'&&selected)change(splitClip(project,selected,time) as Project);
    if(e.code==='Delete'||e.code==='Backspace')remove(e.shiftKey);
  };window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
  const media=project.media.filter(m=>m.name.toLowerCase().includes(search.toLowerCase())&&(leftTab==='audio'?m.type==='audio':true));
  if(loading)return <div className="boot-screen"><span className="brand-icon"><Scissors size={24}/></span><h1>Corte Local</h1><p>Preparando tu espacio de trabajo…</p><LoaderCircle size={20} className="spin"/></div>;
  return <div className="app" onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();}} onDrop={e=>{if(!e.dataTransfer.files.length)return;e.preventDefault();if(api){const paths=Array.from(e.dataTransfer.files).map(f=>api.pathForFile(f));importFiles(paths);}}}>
    <header className="topbar"><div className="brand"><span className="brand-icon"><Scissors size={20}/></span><span>CORTE<span className="brand-light">LOCAL</span></span></div><div className="topbar-divider"/>
      <div className="project-heading"><input aria-label="Nombre del proyecto" value={project.name} onChange={e=>change({...project,name:e.target.value})}/><span className="save-status"><span className={dirty?'dot':'dot saved'}/>{saveState}</span></div>
      <div className="file-menu"><button className="text-button" onClick={()=>setFileMenu(!fileMenu)}>Archivo <ChevronDown size={12}/></button>{fileMenu&&<div className="dropdown"><button onClick={newDocument}><Plus size={14}/> Nuevo proyecto</button><button onClick={()=>open()}><FolderOpen size={14}/> Abrir proyecto</button><button onClick={()=>save()}><Save size={14}/> Guardar <kbd>Ctrl S</kbd></button><button onClick={()=>save(true)}><Copy size={14}/> Guardar como…</button><button onClick={()=>save(false,true)}><Package size={14}/> Recopilar proyecto</button><button onClick={()=>{setModal('projects');setFileMenu(false);refresh();}}><HardDrive size={14}/> Proyectos recientes</button></div>}</div>
      <div className="topbar-spacer"/><span className="local-badge"><ShieldCheck size={13}/> {api?'100% local':'Vista de navegador'}</span><IconButton title="Guardar proyecto" onClick={()=>save()}><Save size={17}/></IconButton><IconButton title="Ajustes" onClick={()=>{setModal('settings');refresh();}}><Settings size={17}/></IconButton><button className="button primary export-button" onClick={()=>{setPlaying(false);setExportOptions({...exportOptions,fps:project.fps,start:0,end:total});setModal('export');}} disabled={!total||busy}><ArrowUpFromLine size={15}/> Exportar</button>
    </header>
    <div className="workspace"><nav className="rail">{[{id:'media',icon:FolderOpen,label:'Archivos'},{id:'audio',icon:Music2,label:'Audio'},{id:'text',icon:Type,label:'Textos'},{id:'captions',icon:Captions,label:'Subtítulos'}].map(t=><button className={leftTab===t.id?'active':''} key={t.id} onClick={()=>setLeftTab(t.id)}><t.icon size={21} strokeWidth={1.6}/><span>{t.label}</span></button>)}<div className="rail-spacer"/><button onClick={()=>setModal('shortcuts')}><Keyboard size={20}/><span>Atajos</span></button></nav>
      <aside className="library">{leftTab==='captions'?<CaptionsPanel project={project} status={status} selected={selected} time={time} change={change} select={setSelected} seek={seek} generate={showTranscribe} importSrt={async()=>{const cues=await safe(()=>api!.importCaptions());if(cues){change({...project,captions:cues,captionStale:false});notify('Subtítulos importados.');}}} exportCues={async format=>{const file=await safe(()=>api!.exportCaptions(project,format));if(file)notify('Subtítulos exportados.');}} savePreset={async name=>{await safe(()=>api!.savePreset(name,project.captionStyle));refresh();}} editStyle={()=>{setSelected(null);setInspectorTab('style');}} busy={busy}/>:leftTab==='text'?<div className="text-library"><div className="panel-heading"><div><h2>Textos</h2><p>Una idea merece un título.</p></div></div><button className="button primary full" onClick={addText}><Plus size={15}/> Añadir texto</button><div className="text-template" onClick={addText}><span>Aa</span><b>Texto personalizado</b><small>Tu fuente. Tu color. Tu mensaje.</small></div><p className="muted">Arrastra el texto sobre el visor para colocarlo. Ajusta su estilo y duración en el panel de propiedades.</p></div>:<>
        <div className="panel-heading"><div><h2>{leftTab==='audio'?'Audio':'Tus archivos'}</h2><p>{leftTab==='audio'?'El ritmo de tu historia.':'Todo empieza con una buena toma.'}</p></div><span className="count-badge">{media.length}</span></div><button className="button primary full import-button" onClick={()=>importFiles()} disabled={importing}>{importing?<LoaderCircle className="spin" size={16}/>:<Plus size={16}/>} {importing?'Preparando archivos…':'Importar archivos'}</button><input className="search" placeholder="Buscar en tu biblioteca" value={search} onChange={e=>setSearch(e.target.value)}/>
        <div className="media-grid">{media.map(m=><div key={m.id} className={`media-card ${m.missing?'missing':''}`} draggable={!m.missing} onDragStart={e=>e.dataTransfer.setData('application/corte-media',m.id)} onDoubleClick={()=>!m.missing&&addMedia(m.id)}>
          <div className="media-thumbnail">{m.thumbnail?<img src={m.thumbnail}/>:m.type==='audio'?<Music2 size={28} strokeWidth={1}/>:<Film size={28} strokeWidth={1}/>}<span className="media-duration">{Math.floor(m.duration/60)}:{String(Math.floor(m.duration%60)).padStart(2,'0')}</span><button className="media-add" title="Añadir a la línea de tiempo" onClick={()=>addMedia(m.id)} disabled={m.missing}><Plus size={15}/></button></div>
          <div className="media-name" title={m.path}>{m.name}</div><span className="media-meta">{m.missing?'Archivo ausente':m.type==='audio'?'Audio':m.type==='image'?'Imagen':`${m.width} × ${m.height}`}</span>
          {m.type!=='audio'&&<button className="media-overlay" title="Superponer en una nueva pista en el cursor" disabled={m.missing} onDoubleClick={e=>e.stopPropagation()} onClick={()=>addMedia(m.id,undefined,timeRef.current,true)}><Layers size={12}/> Superponer</button>}
          <div className="media-actions"><button onClick={async()=>{const fresh=await safe(()=>api!.relink(project,m.id));if(fresh){const next=structuredClone(project);next.media=next.media.map(x=>x.id===m.id?fresh:x);change(next);}}}>{m.missing?'Localizar archivo':'Reemplazar'}</button><button title="Quitar de la biblioteca" onClick={()=>{if(project.clips.some(c=>c.mediaId===m.id)){notify('El archivo está en uso en la línea de tiempo.',true);return;}change({...project,media:project.media.filter(x=>x.id!==m.id)});}}><X size={11}/></button></div>
        </div>)}</div>
        {!media.length&&<div className="library-empty"><div className="empty-file-stack"><Film size={28} strokeWidth={1}/><Image size={18} strokeWidth={1}/></div><h3>Espacio para tus ideas</h3><p>Arrastra vídeos, fotos o audio.<br/>Tus archivos se quedan contigo.</p><small>MP4 · MOV · MP3 · PNG · y más</small></div>}<div className="library-bottom"><HardDrive size={12}/><span>Archivos originales protegidos</span></div>
      </>}</aside>
      <main className="viewer"><div className="viewer-toolbar"><span>VISOR</span><div className="viewer-actions"><select aria-label="Formato del lienzo" value={`${project.width}:${project.height}`} onChange={e=>{const [width,height]=e.target.value.split(':').map(Number);change({...project,width,height});}}><option value="1920:1080">16:9 · Horizontal</option><option value="1080:1920">9:16 · Vertical</option><option value="1080:1080">1:1 · Cuadrado</option><option value="1080:1350">4:5 · Retrato</option></select><select aria-label="Fotogramas del proyecto" value={project.fps} onChange={e=>change({...project,fps:Number(e.target.value)})}>{[24,25,30,60].map(f=><option key={f} value={f}>{f} fps</option>)}</select><input aria-label="Color del lienzo" type="color" value={project.background} onChange={e=>change({...project,background:e.target.value})}/></div></div>
        <Preview key={project.id} project={project} time={time} playing={playing} selected={selected} status={status} select={setSelected} updateClip={updateClip} preview={preview} seek={seek} pause={()=>setPlaying(false)} onError={message=>notify(message,true)}/>
        <div className="transport"><span className="time-display"><b>{timecode(time,project.fps)}</b><span>/ {timecode(total,project.fps)}</span></span><div className="transport-buttons"><IconButton title="Ir al inicio" onClick={()=>{setPlaying(false);seek(0);}}><SkipBack size={15}/></IconButton><IconButton title="Fotograma anterior" onClick={()=>{setPlaying(false);seek(time-1/project.fps);}}><ChevronLeft size={17}/></IconButton><button className="play-button" title={playing?'Pausar':'Reproducir'} aria-label={playing?'Pausar':'Reproducir'} onClick={()=>{if(time>=total)setTime(preview?.start||0);setPlaying(!playing);}} disabled={!total}>{playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}</button><IconButton title="Fotograma siguiente" onClick={()=>{setPlaying(false);seek(time+1/project.fps);}}><ChevronRight size={17}/></IconButton><IconButton title="Ir al final" onClick={()=>{setPlaying(false);seek(total);}}><SkipForward size={15}/></IconButton></div><button className={`render-preview ${preview?'active':''}`} disabled={!total||busy} onClick={()=>preview?setPreview(null):renderPreview()}><Monitor size={13}/>{preview?'Volver al editor':'Vista renderizada'}</button></div>
      </main>
      <Inspector project={project} selected={selected} status={status} update={updateClip} change={change} onFont={addFont} duplicate={duplicate} remove={()=>remove()} detach={detach} tab={inspectorTab} setTab={setInspectorTab}/>
    </div>
    <section className="timeline"><div className="timeline-toolbar"><div className="edit-tools"><IconButton title="Deshacer (Ctrl Z)" onClick={()=>history('undo')} disabled={!historySize[0]}><Undo2 size={16}/></IconButton><IconButton title="Rehacer (Ctrl Y)" onClick={()=>history('redo')} disabled={!historySize[1]}><Redo2 size={16}/></IconButton><span className="separator"/><IconButton title="Dividir clip (B)" onClick={()=>selected&&change(splitClip(project,selected,time) as Project)} disabled={!project.clips.some(c=>c.id===selected)}><Scissors size={16}/></IconButton><IconButton title="Unir cortes consecutivos" onClick={mergeClips} disabled={!selected}><Merge size={16}/></IconButton><IconButton title="Duplicar (Ctrl D)" onClick={duplicate} disabled={!selected}><Copy size={16}/></IconButton><IconButton title="Eliminar (Supr)" onClick={()=>remove()} disabled={!selected}><Trash2 size={16}/></IconButton><IconButton title="Eliminar y cerrar hueco (Mayús Supr)" onClick={()=>remove(true)} disabled={!selected}><ArrowDownToLine size={16}/></IconButton><span className="separator"/><button className="text-button" onClick={addText}><Type size={15}/> Texto</button><button className="text-button" onClick={()=>{setLeftTab('captions');showTranscribe();}} disabled={!project.clips.length}><Captions size={16}/> Subtítulos</button></div><div className="zoom-controls"><span>Ajuste magnético</span><span className="snap-dot"/><IconButton title="Reducir línea de tiempo" onClick={()=>setZoom(z=>Math.max(3,z/1.3))}><Minus size={14}/></IconButton><input aria-label="Zoom de la línea de tiempo" type="range" min={3} max={160} value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><IconButton title="Ampliar línea de tiempo" onClick={()=>setZoom(z=>Math.min(160,z*1.3))}><Plus size={14}/></IconButton><IconButton title="Ajustar todo el proyecto" onClick={()=>setZoom(Math.max(3,(window.innerWidth-190)/Math.max(20,total+5)))}><Maximize2 size={14}/></IconButton></div></div>
      <Timeline project={project} time={time} selected={selected} zoom={zoom} seek={seek} select={setSelected} change={change} addTrack={addTrack} addMedia={addMedia} addOverlay={(id,start)=>addMedia(id,undefined,start,true)} dropFiles={dropFiles} importOverlay={()=>importFiles(undefined,{start:timeRef.current,overlay:true})} importing={importing} captionSelect={id=>{setSelected(id);setLeftTab('captions');}}/>
    </section>
    <footer className="statusbar"><span><span className="dot saved"/> {api?'Sin conexión a servicios externos':'Abre la aplicación de escritorio para editar'}</span><span>{project.clips.length} clips · {project.captions.length} subtítulos</span><span>Hecho para crear. Sin suscripciones.</span></footer>
    {notice&&<div className={`toast ${notice.error?'error':''}`} role="status">{notice.error?<X size={17}/>:<Check size={17}/>}<span>{notice.text}</span><button onClick={()=>setNotice(null)}><X size={15}/></button></div>}
    {(activeJobs.length>0||importing)&&<div className="job-panel">{importing&&<div className="job-item"><LoaderCircle className="spin" size={16}/><div><b>Importando archivos</b><span>Creando miniaturas y una copia ligera…</span></div></div>}{activeJobs.map(j=><div className="job-item" key={j.id}><LoaderCircle className="spin" size={16}/><div><b>{j.kind==='export'?'Exportando vídeo':j.kind==='transcribe'?'Generando subtítulos':j.kind==='preview'?'Preparando vista':'Descarga local'} <span>{Math.round(j.progress*100)}%</span></b><span>{j.message}</span><div className="progress-track"><i style={{width:`${j.progress*100}%`}}/></div></div><IconButton title="Cancelar tarea" onClick={()=>safe(()=>api!.cancelJob(j.id))}><X size={15}/></IconButton></div>)}</div>}
    {jobs.some(j=>j.kind==='export'&&j.state==='done')&&!activeJobs.length&&<div className="export-finished"><Check size={15}/><span>Exportación completada</span><button onClick={()=>safe(()=>api!.reveal(jobs.filter(j=>j.kind==='export'&&j.state==='done').at(-1)!.result.path))}>Ver archivo</button><button onClick={()=>setJobs(j=>j.filter(x=>x.kind!=='export'||x.state!=='done'))}><X size={13}/></button></div>}
    {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&modal!=='recovery')setModal(null);}}><div className={`modal modal-${modal}`} role="dialog" aria-modal="true"><div className="modal-heading"><div><span className="eyebrow">CORTE LOCAL</span><h2>{modal==='settings'?'Tu espacio de trabajo':modal==='export'?'Lista para compartir':modal==='transcribe'?'Dale voz a tus subtítulos':modal==='projects'?'Tus proyectos':modal==='recovery'?'Retoma tu historia':'Trabaja a tu ritmo'}</h2></div>{modal!=='recovery'&&<IconButton title="Cerrar" onClick={()=>setModal(null)}><X size={20}/></IconButton>}</div>
      {modal==='settings'&&<><p className="modal-description">Los motores, modelos y archivos se guardan en tu ordenador. Solo las descargas que solicites necesitan internet.</p><div className="settings-grid"><div className="setting-card"><Monitor size={22}/><b>Motor de vídeo</b><span>{status?.ffmpeg&&status?.ffprobe?'FFmpeg y FFprobe disponibles':'Motor no disponible'}</span><small>Incluido con la aplicación</small></div><div className="setting-card"><Sparkles size={22}/><b>Reconocimiento de voz</b><span>{status?.whisper?'Whisper instalado':'Instala Whisper para transcribir'}</span><button className="button secondary" disabled={busy||status?.whisper} onClick={()=>safe(()=>api!.installWhisper())}>{status?.whisper?'Instalado':'Instalar motor'}</button></div></div><div className="section-label">MODELOS DE VOZ · ESPAÑOL</div>{[{id:'base',name:'Ligero',size:'142 MB',description:'Menor consumo de memoria'},{id:'small',name:'Equilibrado',size:'466 MB',description:'Recomendado para empezar'},{id:'medium',name:'Mayor precisión',size:'1,5 GB',description:'Más memoria y tiempo de proceso'}].map(m=><div className="model-row" key={m.id}><div><b>{m.name} <span>{m.id}</span></b><small>{m.description} · {m.size}</small></div><button className="button secondary" disabled={busy||status?.models.includes(m.id)} onClick={()=>safe(()=>api!.downloadModel(m.id))}>{status?.models.includes(m.id)?<><Check size={14}/> Instalado</>:<><Download size={14}/> Descargar</>}</button></div>)}<div className="settings-bottom"><div><b>Caché local · {status?.cacheMB||0} MB</b><p>Las copias ligeras se regeneran al volver a abrir el proyecto.</p></div><button className="button secondary" disabled={busy||importing} onClick={async()=>{if(window.confirm('Se eliminarán las copias de previsualización. Guarda y vuelve a abrir el proyecto para regenerarlas.')){await safe(()=>api!.clearCache());refresh();notify('Caché limpiada. Vuelve a abrir el proyecto.');}}}>Limpiar caché</button></div><div className="hardware-info"><HardDrive size={14}/> {status?.memoryGB||'—'} GB de RAM · {status?.cpu||'Detección local al abrir la aplicación'}</div></>}
      {modal==='export'&&<><p className="modal-description">Exporta desde los archivos originales, sin marcas de agua.</p><div className="export-preview-card"><Film size={30} strokeWidth={1}/><div><b>{project.name}</b><span>{project.width} × {project.height} · {timecode(total,project.fps)}</span></div></div><div className="field-grid"><Field label="Resolución"><select value={exportOptions.height} onChange={e=>setExportOptions({...exportOptions,height:Number(e.target.value)})}><option value={1080}>1080p · Full HD</option><option value={720}>720p · Ligero</option></select></Field><Field label="Fotogramas por segundo"><select value={exportOptions.fps} onChange={e=>setExportOptions({...exportOptions,fps:Number(e.target.value)})}>{[24,25,30,60].map(n=><option key={n} value={n}>{n} fps</option>)}</select></Field></div><Field label="Calidad"><select value={exportOptions.quality} onChange={e=>setExportOptions({...exportOptions,quality:e.target.value as ExportOptions['quality']})}><option value="high">Alta · mayor detalle</option><option value="standard">Estándar · archivo más pequeño</option></select></Field><div className="field-grid"><NumberField label="Desde (s)" value={exportOptions.start} max={Math.max(0,exportOptions.end-0.05)} onChange={start=>setExportOptions({...exportOptions,start})}/><NumberField label="Hasta (s)" value={exportOptions.end} min={exportOptions.start+0.05} max={total} onChange={end=>setExportOptions({...exportOptions,end})}/></div><label className="checkbox"><input type="checkbox" checked={exportOptions.burnCaptions} onChange={e=>setExportOptions({...exportOptions,burnCaptions:e.target.checked})}/> Incrustar subtítulos en el vídeo</label><label className="checkbox"><input type="checkbox" checked={exportOptions.normalize} onChange={e=>setExportOptions({...exportOptions,normalize:e.target.checked})}/> Normalizar volumen a −16 LUFS</label><p className="muted">MP4 · H.264 · AAC{!exportOptions.burnCaptions?' · Subtítulos en un archivo SRT separado':''}</p><button className="button primary full modal-action" disabled={busy} onClick={async()=>{const id=await safe(()=>api!.exportVideo(project,exportOptions));if(id)setModal(null);}}><ArrowUpFromLine size={16}/> Elegir ubicación y exportar</button></>}
      {modal==='transcribe'&&<><p className="modal-description">Transcripción por frases en español. Selecciona las pistas que contienen voz y excluye la música.</p>{(!status?.whisper||!status?.models.length)?<div className="setup-needed"><Sparkles size={28}/><b>Prepara el reconocimiento local</b><p>Instala Whisper y descarga un modelo una vez. Después podrás transcribir sin internet.</p><button className="button primary" onClick={()=>{setModal('settings');refresh();}}>Configurar motor y modelo</button></div>:<><Field label="Modelo"><select value={status.models.includes(model)?model:status.models[0]} onChange={e=>setModel(e.target.value)}>{status.models.map(m=><option key={m} value={m}>{m==='small'?'Equilibrado':m==='base'?'Ligero':'Mayor precisión'} · {m}</option>)}</select></Field><div className="section-label">PISTAS DE VOZ</div>{project.tracks.filter(t=>project.clips.some(c=>c.trackId===t.id&&project.media.find(m=>m.id===c.mediaId)?.hasAudio)).map(t=><label className="checkbox voice-track" key={t.id}><input type="checkbox" disabled={t.muted} checked={voiceTracks.includes(t.id)} onChange={e=>setVoiceTracks(e.target.checked?[...voiceTracks,t.id]:voiceTracks.filter(id=>id!==t.id))}/>{t.name}{t.muted&&<small>Silenciada</small>}</label>)}<div className="field-grid"><NumberField label="Desde (s)" value={transcribeRange.start} max={transcribeRange.end-0.05} onChange={start=>setTranscribeRange({...transcribeRange,start})}/><NumberField label="Hasta (s)" value={transcribeRange.end} min={transcribeRange.start+0.05} max={total} onChange={end=>setTranscribeRange({...transcribeRange,end})}/></div>{project.captions.some(c=>c.end>transcribeRange.start&&c.start<transcribeRange.end)&&<label className="checkbox replace-warning"><input type="checkbox" checked={replaceCaptions} onChange={e=>setReplaceCaptions(e.target.checked)}/> Sustituir los subtítulos y sus correcciones en este tramo</label>}<button className="button primary full modal-action" disabled={busy||!voiceTracks.length} onClick={()=>{if(!status.models.includes(model))setModel(status.models[0]);transcribe();}}><Sparkles size={16}/> Generar subtítulos</button></>}</>}
      {modal==='projects'&&<><button className="button secondary full" onClick={()=>open()}><FolderOpen size={15}/> Abrir un archivo de proyecto</button><div className="recent-list">{status?.recent.map(r=><button key={r.path} onClick={()=>open(r.path)}><Clapperboard size={22}/><div><b>{r.name}</b><span>{r.path}</span></div><small>{new Date(r.updated).toLocaleDateString('es')}</small></button>)}{!status?.recent.length&&<p className="muted">Tus proyectos guardados aparecerán aquí.</p>}</div></>}
      {modal==='recovery'&&<><p className="modal-description">Hay una copia de trabajo guardada de <b>{status?.recovery?.name}</b>. Puedes recuperarla o empezar un proyecto nuevo.</p><div className="modal-buttons"><button className="button secondary" onClick={()=>{setModal(null);safe(()=>api!.clearRecovery());}}>Empezar de nuevo</button><button className="button primary" onClick={()=>{if(status?.recovery){load(status.recovery);setDirty(true);}}}>Recuperar proyecto</button></div></>}
      {modal==='shortcuts'&&<div className="shortcut-list">{[['Reproducir / pausar','Espacio'],['Dividir clip en el cursor','B'],['Eliminar clip','Supr'],['Eliminar y cerrar hueco','Mayús + Supr'],['Duplicar clip','Ctrl + D'],['Deshacer / rehacer','Ctrl + Z / Ctrl + Y'],['Guardar / guardar como','Ctrl + S / Ctrl + Mayús + S'],['Avanzar / retroceder un fotograma','← / →']].map(([action,key])=><div key={key}><span>{action}</span><kbd>{key}</kbd></div>)}</div>}
    </div></div>}
  </div>;
}
